#-------------------------------
# General Site Settings
title: Elon Mask
baseurl: "/elonmask" # the subpath of your site, e.g. /blog
url: "https://gloyns.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 8
paginate_path: "/blog/page/:num"


#-------------------------------
# Collections
collections:
  features:
    output: true
    permalink: /features/:name
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed